-- Baycast Questions Batch: May 15, 2026
-- 15 questions across 7 categories
-- Resolution window: Jun 2026 – Jan 2027

INSERT INTO questions (title, description, category, options, resolution_date, resolution_source, status, created_by) VALUES
('Will SpaceX complete its IPO before January 1, 2027?', 'Will SpaceX file an S-1 or equivalent and complete an initial public offering on a major US exchange (NYSE/NASDAQ) before January 1, 2027?', 'Tech', '["Yes","No"]', '2027-01-01', 'https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=SPACEX', 'active', 'baycast-system'),
('Will OpenAI release a model branded as GPT-6 (or equivalent next-gen flagship) before December 31, 2026?', 'OpenAI must officially announce and make available a next-generation flagship model branded as GPT-6, o3, or equivalent before December 31, 2026.', 'Tech', '["Yes","No"]', '2026-12-31', 'https://openai.com/blog', 'active', 'baycast-system'),
('Will Apple announce a second-generation Vision Pro before December 31, 2026?', 'Apple must officially announce a second-generation Vision Pro or equivalent AR/VR headset at an Apple event or press release before December 31, 2026.', 'Tech', '["Yes","No"]', '2026-12-31', 'https://www.apple.com/newsroom/', 'active', 'baycast-system'),
('Will a formal ceasefire or peace agreement between the US/Israel coalition and Iran be signed before September 30, 2026?', 'A formal, publicly announced ceasefire or peace agreement must be signed by representatives of the US, Israel, and Iran (or Iran proxies) before September 30, 2026.', 'Géopolitique', '["Yes","No"]', '2026-09-30', 'https://www.state.gov; https://reuters.com', 'active', 'baycast-system'),
('Will TikTok remain fully operational in the US under ByteDance ownership on December 31, 2026?', 'TikTok must be available for download and use in the US on both iOS and Android app stores, operated by ByteDance or its subsidiary, on December 31, 2026.', 'Géopolitique', '["Yes","No"]', '2026-12-31', 'https://apps.apple.com; https://play.google.com; Congressional Record', 'active', 'baycast-system'),
('Will the US Federal Reserve cut the federal funds rate at least once before December 31, 2026?', 'The Fed must announce a decrease in the target federal funds rate at any FOMC meeting before December 31, 2026.', 'Économie', '["Yes","No"]', '2026-12-31', 'https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm', 'active', 'baycast-system'),
('Will the US unemployment rate exceed 5.0% at any point before December 31, 2026?', 'The Bureau of Labor Statistics seasonally adjusted U-3 unemployment rate must exceed 5.0% in any monthly report published before December 31, 2026.', 'Économie', '["Yes","No"]', '2026-12-31', 'https://www.bls.gov/news.release/empsit.nr0.htm', 'active', 'baycast-system'),
('Will SpaceX Starship successfully complete an orbital flight with booster catch before September 30, 2026?', 'SpaceX Starship must complete a full orbital trajectory and the Super Heavy booster must successfully be caught by the chopstick arms at the launch tower in a single mission before September 30, 2026.', 'Sciences', '["Yes","No"]', '2026-09-30', 'https://www.spacex.com/launches/', 'active', 'baycast-system'),
('Will the WHO officially declare human-to-human transmission of H5N1 avian influenza before December 31, 2026?', 'The WHO Director-General must issue an official statement or PHEIC declaration confirming sustained human-to-human transmission of H5N1 before December 31, 2026.', 'Sciences', '["Yes","No"]', '2026-12-31', 'https://www.who.int/emergencies/disease-outbreak-news', 'active', 'baycast-system'),
('Will a South American team win the 2026 FIFA World Cup?', 'A national team from CONMEBOL (South America) must win the 2026 FIFA World Cup final on July 19, 2026.', 'Sport', '["Yes","No"]', '2026-07-19', 'https://www.fifa.com/fifaplus/en/tournaments/mens/worldcup/2026', 'active', 'baycast-system'),
('Will Jannik Sinner win any Grand Slam singles title in 2026?', 'Jannik Sinner must win the mens singles title at any of the four 2026 Grand Slam tournaments (Australian Open, Roland Garros, Wimbledon, US Open).', 'Sport', '["Yes","No"]', '2026-12-31', 'https://www.atptour.com/en/tournaments', 'active', 'baycast-system'),
('Will any 2026 film surpass $1.5 billion in worldwide box office?', 'Any film with a 2026 theatrical release date must surpass $1.5 billion in cumulative worldwide box office gross (as reported by Box Office Mojo) by January 15, 2027.', 'Culture', '["Yes","No"]', '2027-01-15', 'https://www.boxofficemojo.com/year/world/2026/', 'active', 'baycast-system'),
('Will Eon Productions announce the lead actor for Bond 26 before December 31, 2026?', 'Eon Productions or Amazon MGM must issue an official press release naming the actor cast as James Bond in Bond 26 before December 31, 2026.', 'Culture', '["Yes","No"]', '2026-12-31', 'https://www.007.com/', 'active', 'baycast-system'),
('Will Bitcoin (BTC) reach or exceed $150,000 USD before December 31, 2026?', 'Bitcoin (BTC/USD) daily UTC close price must reach or exceed $150,000 on any day before December 31, 2026, as reported by CoinGecko.', 'Crypto', '["Yes","No"]', '2026-12-31', 'https://www.coingecko.com/en/coins/bitcoin', 'active', 'baycast-system'),
('Will a Solana (SOL) spot ETF be approved by US regulators before December 31, 2026?', 'The US SEC must issue a final order approving a spot Solana ETF (19b-4 or S-1 effective) before December 31, 2026.', 'Crypto', '["Yes","No"]', '2026-12-31', 'https://www.sec.gov/rules/final.shtml', 'active', 'baycast-system');
